import { StyleSheet } from 'react-native';
import { AppColors } from '../constants/theme';
import { HeroLayout } from '../constants/heroLayout';

const { cardPadding, posterScale, posterWidth, posterHeight, infoTopOffset, screenWidth } =
  HeroLayout;

export const heroStyles = StyleSheet.create({
  container: {
    backgroundColor: AppColors.background,
    paddingBottom: 12,
  },
  statusBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: cardPadding,
    paddingTop: 12,
    paddingBottom: 4,
  },
  statusTime: {
    color: AppColors.textPrimary,
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: -0.3,
  },
  statusIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: cardPadding,
    paddingTop: 10,
    paddingBottom: 20,
  },
  logoImg: {
    width: 80,
    height: 80,
    borderRadius: 14,
  },
  bellBtn: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  slidePage: {
    width: screenWidth,
  },
  card: {
    flexDirection: 'row',
    paddingHorizontal: cardPadding,
    gap: HeroLayout.cardGap,
    alignItems: 'flex-start',
  },
  posterWrapper: {
    width: posterWidth,
    height: posterHeight,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#1a1a1a',
  },
  posterImg: {
    width: '100%',
    height: '100%',
  },
  posterDim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(12, 22, 48, 0.38)',
  },
  bannerStrip: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0,0,0,0.55)',
    paddingVertical: 6,
    alignItems: 'center',
  },
  bannerText: {
    color: AppColors.textPrimary,
    fontSize: 9 * posterScale,
    fontWeight: '700',
    letterSpacing: 0.6,
  },
  posterArtBlock: {
    position: 'absolute',
    left: 2,
    right: 2,
    top: '27%',
    alignItems: 'center',
  },
  posterArtRed: {
    color: '#DC2626',
    fontSize: 8 * posterScale,
    lineHeight: 10.5 * posterScale,
    fontWeight: '900',
    textAlign: 'center',
    letterSpacing: 0.15,
    textTransform: 'uppercase',
  },
  posterArtWhiteLine: {
    marginTop: 4,
    color: AppColors.textPrimary,
    fontSize: 11 * posterScale,
    lineHeight: 13 * posterScale,
    fontWeight: '900',
    textAlign: 'center',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  posterArtMotion: {
    marginTop: 10,
    color: '#DC2626',
    fontSize: 7 * posterScale,
    lineHeight: 9 * posterScale,
    fontWeight: '800',
    textAlign: 'center',
    letterSpacing: 0.25,
    textTransform: 'uppercase',
  },
  posterAgeBadge: {
    position: 'absolute',
    bottom: 8,
    left: 8,
    backgroundColor: 'rgba(0,0,0,0.7)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  posterAgeText: {
    color: AppColors.textPrimary,
    fontSize: 9 * posterScale,
    fontWeight: '700',
  },
  infoCol: {
    flex: 1,
    minWidth: 0,
    height: posterHeight,
    justifyContent: 'flex-start',
    paddingTop: infoTopOffset,
  },
  title: {
    color: AppColors.textPrimary,
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 25,
    letterSpacing: -0.1,
  },
  desc: {
    marginTop: 4,
    color: AppColors.textMuted,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '400',
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
  },
  ratingItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  ratingItemGap: {
    marginLeft: 12,
  },
  kpIconWrap: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#0D0D0D',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imdbBadge: {
    backgroundColor: '#F5C518',
    borderRadius: 4,
    paddingHorizontal: 5,
    paddingVertical: 2,
    height: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  imdbText: {
    color: '#000',
    fontSize: 9,
    fontWeight: '800',
    lineHeight: 11,
  },
  ratingNum: {
    color: AppColors.textPrimary,
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 18,
  },
  tagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 10,
  },
  tag: {
    paddingHorizontal: 12,
    overflow: 'hidden',
    paddingVertical: 6,
    borderRadius: 14,
  },
  tagText: {
    color: AppColors.textPrimary,
    fontSize: 13,
    fontWeight: '500',
  },
  dotsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
    marginTop: 22,
    paddingBottom: 6,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(255,255,255,0.3)',
  },
  dotActive: {
    width: 28,
    height: 8,
    borderRadius: 4,
    backgroundColor: AppColors.textPrimary,
  },
});
